service:
  name: serverless-training

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpackConfig: ./webpack.config.js
  includeModules: true

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x
  region: sa-east-1

functions:
  hello: 
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: GET
          cors: true
